<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.5.7</version>
        <relativePath/>
    </parent>

    <groupId>com.jss</groupId>
    <artifactId>devices-manager-parent</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>Device Manager Parent</name>
    <description>Device tracking system - Multi-module project</description>

    <properties>
        <java.version>25</java.version>
        <swagger-annotations.version>2.2.40</swagger-annotations.version>
        <jackson-databind-nullable.version>0.2.8</jackson-databind-nullable.version>
        <openapi-generator-maven-plugin.version>7.17.0</openapi-generator-maven-plugin.version>
    </properties>

    <modules>
        <module>services/common</module>
        <module>services/statistics-api</module>
        <module>services/device-registration-api</module>
    </modules>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
