# Development profile configuration
logging.level.com.jss.devicemanager=DEBUG

# Device Registration API configuration
device.registration.api.url=http://localhost:8081
device.registration.api.key=00000000-0000-0000-0000-000000000000
