services:
  mariadb:
    image: mariadb:latest
    container_name: devices-manager-db
    network_mode: host
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 3

  statistics-api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.statistics-api
    container_name: statistics-api
    network_mode: host
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SERVER_PORT: ${STATISTICS_API_PORT}
      SPRING_DATASOURCE_URL: jdbc:mariadb://localhost:${MYSQL_PORT}/${MYSQL_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      DEVICE_REGISTRATION_API_URL: http://localhost:${DEVICE_REGISTRATION_API_PORT}
      DEVICE_REGISTRATION_API_KEY: ${DEVICE_REGISTRATION_API_KEY}
    depends_on:
      mariadb:
        condition: service_healthy

  device-registration-api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.device-registration-api
    container_name: device-registration-api
    network_mode: host
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SERVER_PORT: ${DEVICE_REGISTRATION_API_PORT}
      SPRING_DATASOURCE_URL: jdbc:mariadb://localhost:${MYSQL_PORT}/${MYSQL_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      DEVICE_REGISTRATION_API_KEY: ${DEVICE_REGISTRATION_API_KEY}
    depends_on:
      mariadb:
        condition: service_healthy

volumes:
  mariadb_data:
